### ISSUE TITLE
twitter-typeahead на главной. Блок с suggestions перекрывает input

### ISSUE THREAD

**Issue by greeceruit** [nicothin/nesia#37]
Нужно стилизовать выпадающий блок typeahead. 
![Screenshot from 2025-01-14 17-30-45](https://github.com/user-attachments/assets/b718e369-cb9a-47fd-9482-6b410d83ea9d)

https://ru.terranesia.com

@vladimir075 , может есть какие-то пожелания к внешнему виду?

**Comment by vladimir075** [comment]
Пожеланий к внешнему виду нет

**Comment by nicothin** [comment]
что-ж.

минимальными действиями будет добавление вот такого фрагмента CSS:

```css
.home_search_form {

  .form-inline {
    display: inline-flex;
  }

  .twitter-typeahead {
    flex-grow: 1;
  }

  #search-btn {
    margin-left: 10px;
  }

  .form-inline .tt-menu.tt-open {
    left: -5px !important;
    right: -5px;
  }
}
```

или, если нужно поддерживать старые браузеры, вот эквивалент:

```css
.home_search_form .form-inline {
  display: inline-flex;
}

.home_search_form .twitter-typeahead {
  flex-grow: 1;
}

.home_search_form #search-btn {
  margin-left: 10px;
}

.home_search_form .form-inline .tt-menu.tt-open {
  left: -5px !important;
  right: -5px;
}
```
